// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// FollowsColumns holds the columns for the "follows" table.
	FollowsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "follower_id", Type: field.TypeString},
		{Name: "following_id", Type: field.TypeString},
	}
	// FollowsTable holds the schema information for the "follows" table.
	FollowsTable = &schema.Table{
		Name:       "follows",
		Columns:    FollowsColumns,
		PrimaryKey: []*schema.Column{FollowsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "follows_users_sent_follows",
				Columns:    []*schema.Column{FollowsColumns[3]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "follows_users_received_follows",
				Columns:    []*schema.Column{FollowsColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "follow_follower_id_following_id",
				Unique:  true,
				Columns: []*schema.Column{FollowsColumns[3], FollowsColumns[4]},
			},
			{
				Name:    "follow_follower_id",
				Unique:  false,
				Columns: []*schema.Column{FollowsColumns[3]},
			},
			{
				Name:    "follow_following_id",
				Unique:  false,
				Columns: []*schema.Column{FollowsColumns[4]},
			},
		},
	}
	// NotificationsColumns holds the columns for the "notifications" table.
	NotificationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "recipient_id", Type: field.TypeString},
		{Name: "actor_id", Type: field.TypeString},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"follow", "like", "comment", "mention", "friend"}, Default: "follow"},
		{Name: "entity_type", Type: field.TypeString},
		{Name: "entity_id", Type: field.TypeString},
		{Name: "data", Type: field.TypeString, Nullable: true, Size: 2147483647, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "read_at", Type: field.TypeTime, Nullable: true},
	}
	// NotificationsTable holds the schema information for the "notifications" table.
	NotificationsTable = &schema.Table{
		Name:       "notifications",
		Columns:    NotificationsColumns,
		PrimaryKey: []*schema.Column{NotificationsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "notification_recipient_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{NotificationsColumns[3], NotificationsColumns[1]},
			},
			{
				Name:    "notification_recipient_id_read_at",
				Unique:  false,
				Columns: []*schema.Column{NotificationsColumns[3], NotificationsColumns[9]},
			},
			{
				Name:    "notification_recipient_id_type_entity_id",
				Unique:  true,
				Columns: []*schema.Column{NotificationsColumns[3], NotificationsColumns[5], NotificationsColumns[7]},
			},
		},
	}
	// RefreshTokensColumns holds the columns for the "refresh_tokens" table.
	RefreshTokensColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "token_hash", Type: field.TypeString, Unique: true},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "revoked_at", Type: field.TypeTime, Nullable: true},
		{Name: "replaced_by", Type: field.TypeString, Nullable: true},
		{Name: "user_refresh_tokens", Type: field.TypeString},
	}
	// RefreshTokensTable holds the schema information for the "refresh_tokens" table.
	RefreshTokensTable = &schema.Table{
		Name:       "refresh_tokens",
		Columns:    RefreshTokensColumns,
		PrimaryKey: []*schema.Column{RefreshTokensColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "refresh_tokens_users_refresh_tokens",
				Columns:    []*schema.Column{RefreshTokensColumns[7]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "refreshtoken_expires_at",
				Unique:  false,
				Columns: []*schema.Column{RefreshTokensColumns[4]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "name", Type: field.TypeString},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password", Type: field.TypeString},
		{Name: "username", Type: field.TypeString, Unique: true, Nullable: true},
		{Name: "provider", Type: field.TypeEnum, Enums: []string{"google", "github", "email"}, Default: "google"},
		{Name: "email_verified", Type: field.TypeBool, Default: false},
		{Name: "bio", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "varchar(280)"}},
		{Name: "avatar_url", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "varchar(1000)"}},
		{Name: "banner_url", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "varchar(1000)"}},
		{Name: "location", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "varchar(100)"}},
		{Name: "website", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "varchar(200)"}},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		FollowsTable,
		NotificationsTable,
		RefreshTokensTable,
		UsersTable,
	}
)

func init() {
	FollowsTable.ForeignKeys[0].RefTable = UsersTable
	FollowsTable.ForeignKeys[1].RefTable = UsersTable
	RefreshTokensTable.ForeignKeys[0].RefTable = UsersTable
}
