// Code generated by ent, DO NOT EDIT.

package ent

import (
	"ArifulProtik/TownHall/ent/follow"
	"ArifulProtik/TownHall/ent/predicate"
	"ArifulProtik/TownHall/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FollowUpdate is the builder for updating Follow entities.
type FollowUpdate struct {
	config
	hooks    []Hook
	mutation *FollowMutation
}

// Where appends a list predicates to the FollowUpdate builder.
func (_u *FollowUpdate) Where(ps ...predicate.Follow) *FollowUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *FollowUpdate) SetCreatedAt(v time.Time) *FollowUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *FollowUpdate) SetNillableCreatedAt(v *time.Time) *FollowUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FollowUpdate) SetUpdatedAt(v time.Time) *FollowUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetFollowerID sets the "follower_id" field.
func (_u *FollowUpdate) SetFollowerID(v string) *FollowUpdate {
	_u.mutation.SetFollowerID(v)
	return _u
}

// SetNillableFollowerID sets the "follower_id" field if the given value is not nil.
func (_u *FollowUpdate) SetNillableFollowerID(v *string) *FollowUpdate {
	if v != nil {
		_u.SetFollowerID(*v)
	}
	return _u
}

// SetFollowingID sets the "following_id" field.
func (_u *FollowUpdate) SetFollowingID(v string) *FollowUpdate {
	_u.mutation.SetFollowingID(v)
	return _u
}

// SetNillableFollowingID sets the "following_id" field if the given value is not nil.
func (_u *FollowUpdate) SetNillableFollowingID(v *string) *FollowUpdate {
	if v != nil {
		_u.SetFollowingID(*v)
	}
	return _u
}

// SetFollower sets the "follower" edge to the User entity.
func (_u *FollowUpdate) SetFollower(v *User) *FollowUpdate {
	return _u.SetFollowerID(v.ID)
}

// SetFollowing sets the "following" edge to the User entity.
func (_u *FollowUpdate) SetFollowing(v *User) *FollowUpdate {
	return _u.SetFollowingID(v.ID)
}

// Mutation returns the FollowMutation object of the builder.
func (_u *FollowUpdate) Mutation() *FollowMutation {
	return _u.mutation
}

// ClearFollower clears the "follower" edge to the User entity.
func (_u *FollowUpdate) ClearFollower() *FollowUpdate {
	_u.mutation.ClearFollower()
	return _u
}

// ClearFollowing clears the "following" edge to the User entity.
func (_u *FollowUpdate) ClearFollowing() *FollowUpdate {
	_u.mutation.ClearFollowing()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FollowUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FollowUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FollowUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FollowUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FollowUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := follow.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FollowUpdate) check() error {
	if v, ok := _u.mutation.FollowerID(); ok {
		if err := follow.FollowerIDValidator(v); err != nil {
			return &ValidationError{Name: "follower_id", err: fmt.Errorf(`ent: validator failed for field "Follow.follower_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FollowingID(); ok {
		if err := follow.FollowingIDValidator(v); err != nil {
			return &ValidationError{Name: "following_id", err: fmt.Errorf(`ent: validator failed for field "Follow.following_id": %w`, err)}
		}
	}
	if _u.mutation.FollowerCleared() && len(_u.mutation.FollowerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Follow.follower"`)
	}
	if _u.mutation.FollowingCleared() && len(_u.mutation.FollowingIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Follow.following"`)
	}
	return nil
}

func (_u *FollowUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(follow.Table, follow.Columns, sqlgraph.NewFieldSpec(follow.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(follow.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(follow.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.FollowerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   follow.FollowerTable,
			Columns: []string{follow.FollowerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FollowerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   follow.FollowerTable,
			Columns: []string{follow.FollowerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FollowingCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   follow.FollowingTable,
			Columns: []string{follow.FollowingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FollowingIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   follow.FollowingTable,
			Columns: []string{follow.FollowingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{follow.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FollowUpdateOne is the builder for updating a single Follow entity.
type FollowUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FollowMutation
}

// SetCreatedAt sets the "created_at" field.
func (_u *FollowUpdateOne) SetCreatedAt(v time.Time) *FollowUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *FollowUpdateOne) SetNillableCreatedAt(v *time.Time) *FollowUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FollowUpdateOne) SetUpdatedAt(v time.Time) *FollowUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetFollowerID sets the "follower_id" field.
func (_u *FollowUpdateOne) SetFollowerID(v string) *FollowUpdateOne {
	_u.mutation.SetFollowerID(v)
	return _u
}

// SetNillableFollowerID sets the "follower_id" field if the given value is not nil.
func (_u *FollowUpdateOne) SetNillableFollowerID(v *string) *FollowUpdateOne {
	if v != nil {
		_u.SetFollowerID(*v)
	}
	return _u
}

// SetFollowingID sets the "following_id" field.
func (_u *FollowUpdateOne) SetFollowingID(v string) *FollowUpdateOne {
	_u.mutation.SetFollowingID(v)
	return _u
}

// SetNillableFollowingID sets the "following_id" field if the given value is not nil.
func (_u *FollowUpdateOne) SetNillableFollowingID(v *string) *FollowUpdateOne {
	if v != nil {
		_u.SetFollowingID(*v)
	}
	return _u
}

// SetFollower sets the "follower" edge to the User entity.
func (_u *FollowUpdateOne) SetFollower(v *User) *FollowUpdateOne {
	return _u.SetFollowerID(v.ID)
}

// SetFollowing sets the "following" edge to the User entity.
func (_u *FollowUpdateOne) SetFollowing(v *User) *FollowUpdateOne {
	return _u.SetFollowingID(v.ID)
}

// Mutation returns the FollowMutation object of the builder.
func (_u *FollowUpdateOne) Mutation() *FollowMutation {
	return _u.mutation
}

// ClearFollower clears the "follower" edge to the User entity.
func (_u *FollowUpdateOne) ClearFollower() *FollowUpdateOne {
	_u.mutation.ClearFollower()
	return _u
}

// ClearFollowing clears the "following" edge to the User entity.
func (_u *FollowUpdateOne) ClearFollowing() *FollowUpdateOne {
	_u.mutation.ClearFollowing()
	return _u
}

// Where appends a list predicates to the FollowUpdate builder.
func (_u *FollowUpdateOne) Where(ps ...predicate.Follow) *FollowUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FollowUpdateOne) Select(field string, fields ...string) *FollowUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Follow entity.
func (_u *FollowUpdateOne) Save(ctx context.Context) (*Follow, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FollowUpdateOne) SaveX(ctx context.Context) *Follow {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FollowUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FollowUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FollowUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := follow.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FollowUpdateOne) check() error {
	if v, ok := _u.mutation.FollowerID(); ok {
		if err := follow.FollowerIDValidator(v); err != nil {
			return &ValidationError{Name: "follower_id", err: fmt.Errorf(`ent: validator failed for field "Follow.follower_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FollowingID(); ok {
		if err := follow.FollowingIDValidator(v); err != nil {
			return &ValidationError{Name: "following_id", err: fmt.Errorf(`ent: validator failed for field "Follow.following_id": %w`, err)}
		}
	}
	if _u.mutation.FollowerCleared() && len(_u.mutation.FollowerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Follow.follower"`)
	}
	if _u.mutation.FollowingCleared() && len(_u.mutation.FollowingIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Follow.following"`)
	}
	return nil
}

func (_u *FollowUpdateOne) sqlSave(ctx context.Context) (_node *Follow, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(follow.Table, follow.Columns, sqlgraph.NewFieldSpec(follow.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Follow.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, follow.FieldID)
		for _, f := range fields {
			if !follow.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != follow.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(follow.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(follow.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.FollowerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   follow.FollowerTable,
			Columns: []string{follow.FollowerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FollowerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   follow.FollowerTable,
			Columns: []string{follow.FollowerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FollowingCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   follow.FollowingTable,
			Columns: []string{follow.FollowingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FollowingIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   follow.FollowingTable,
			Columns: []string{follow.FollowingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Follow{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{follow.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
