// Code generated by ent, DO NOT EDIT.

package ent

import (
	"ArifulProtik/TownHall/ent/notification"
	"ArifulProtik/TownHall/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NotificationUpdate is the builder for updating Notification entities.
type NotificationUpdate struct {
	config
	hooks    []Hook
	mutation *NotificationMutation
}

// Where appends a list predicates to the NotificationUpdate builder.
func (_u *NotificationUpdate) Where(ps ...predicate.Notification) *NotificationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *NotificationUpdate) SetCreatedAt(v time.Time) *NotificationUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableCreatedAt(v *time.Time) *NotificationUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NotificationUpdate) SetUpdatedAt(v time.Time) *NotificationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetRecipientID sets the "recipient_id" field.
func (_u *NotificationUpdate) SetRecipientID(v string) *NotificationUpdate {
	_u.mutation.SetRecipientID(v)
	return _u
}

// SetNillableRecipientID sets the "recipient_id" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableRecipientID(v *string) *NotificationUpdate {
	if v != nil {
		_u.SetRecipientID(*v)
	}
	return _u
}

// SetActorID sets the "actor_id" field.
func (_u *NotificationUpdate) SetActorID(v string) *NotificationUpdate {
	_u.mutation.SetActorID(v)
	return _u
}

// SetNillableActorID sets the "actor_id" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableActorID(v *string) *NotificationUpdate {
	if v != nil {
		_u.SetActorID(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *NotificationUpdate) SetType(v notification.Type) *NotificationUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableType(v *notification.Type) *NotificationUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetEntityType sets the "entity_type" field.
func (_u *NotificationUpdate) SetEntityType(v string) *NotificationUpdate {
	_u.mutation.SetEntityType(v)
	return _u
}

// SetNillableEntityType sets the "entity_type" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableEntityType(v *string) *NotificationUpdate {
	if v != nil {
		_u.SetEntityType(*v)
	}
	return _u
}

// SetEntityID sets the "entity_id" field.
func (_u *NotificationUpdate) SetEntityID(v string) *NotificationUpdate {
	_u.mutation.SetEntityID(v)
	return _u
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableEntityID(v *string) *NotificationUpdate {
	if v != nil {
		_u.SetEntityID(*v)
	}
	return _u
}

// SetData sets the "data" field.
func (_u *NotificationUpdate) SetData(v string) *NotificationUpdate {
	_u.mutation.SetData(v)
	return _u
}

// SetNillableData sets the "data" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableData(v *string) *NotificationUpdate {
	if v != nil {
		_u.SetData(*v)
	}
	return _u
}

// ClearData clears the value of the "data" field.
func (_u *NotificationUpdate) ClearData() *NotificationUpdate {
	_u.mutation.ClearData()
	return _u
}

// SetReadAt sets the "read_at" field.
func (_u *NotificationUpdate) SetReadAt(v time.Time) *NotificationUpdate {
	_u.mutation.SetReadAt(v)
	return _u
}

// SetNillableReadAt sets the "read_at" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableReadAt(v *time.Time) *NotificationUpdate {
	if v != nil {
		_u.SetReadAt(*v)
	}
	return _u
}

// ClearReadAt clears the value of the "read_at" field.
func (_u *NotificationUpdate) ClearReadAt() *NotificationUpdate {
	_u.mutation.ClearReadAt()
	return _u
}

// Mutation returns the NotificationMutation object of the builder.
func (_u *NotificationUpdate) Mutation() *NotificationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NotificationUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotificationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NotificationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotificationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NotificationUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := notification.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NotificationUpdate) check() error {
	if v, ok := _u.mutation.RecipientID(); ok {
		if err := notification.RecipientIDValidator(v); err != nil {
			return &ValidationError{Name: "recipient_id", err: fmt.Errorf(`ent: validator failed for field "Notification.recipient_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ActorID(); ok {
		if err := notification.ActorIDValidator(v); err != nil {
			return &ValidationError{Name: "actor_id", err: fmt.Errorf(`ent: validator failed for field "Notification.actor_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := notification.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Notification.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EntityType(); ok {
		if err := notification.EntityTypeValidator(v); err != nil {
			return &ValidationError{Name: "entity_type", err: fmt.Errorf(`ent: validator failed for field "Notification.entity_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EntityID(); ok {
		if err := notification.EntityIDValidator(v); err != nil {
			return &ValidationError{Name: "entity_id", err: fmt.Errorf(`ent: validator failed for field "Notification.entity_id": %w`, err)}
		}
	}
	return nil
}

func (_u *NotificationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notification.Table, notification.Columns, sqlgraph.NewFieldSpec(notification.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(notification.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(notification.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RecipientID(); ok {
		_spec.SetField(notification.FieldRecipientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActorID(); ok {
		_spec.SetField(notification.FieldActorID, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(notification.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.EntityType(); ok {
		_spec.SetField(notification.FieldEntityType, field.TypeString, value)
	}
	if value, ok := _u.mutation.EntityID(); ok {
		_spec.SetField(notification.FieldEntityID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Data(); ok {
		_spec.SetField(notification.FieldData, field.TypeString, value)
	}
	if _u.mutation.DataCleared() {
		_spec.ClearField(notification.FieldData, field.TypeString)
	}
	if value, ok := _u.mutation.ReadAt(); ok {
		_spec.SetField(notification.FieldReadAt, field.TypeTime, value)
	}
	if _u.mutation.ReadAtCleared() {
		_spec.ClearField(notification.FieldReadAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NotificationUpdateOne is the builder for updating a single Notification entity.
type NotificationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NotificationMutation
}

// SetCreatedAt sets the "created_at" field.
func (_u *NotificationUpdateOne) SetCreatedAt(v time.Time) *NotificationUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableCreatedAt(v *time.Time) *NotificationUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NotificationUpdateOne) SetUpdatedAt(v time.Time) *NotificationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetRecipientID sets the "recipient_id" field.
func (_u *NotificationUpdateOne) SetRecipientID(v string) *NotificationUpdateOne {
	_u.mutation.SetRecipientID(v)
	return _u
}

// SetNillableRecipientID sets the "recipient_id" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableRecipientID(v *string) *NotificationUpdateOne {
	if v != nil {
		_u.SetRecipientID(*v)
	}
	return _u
}

// SetActorID sets the "actor_id" field.
func (_u *NotificationUpdateOne) SetActorID(v string) *NotificationUpdateOne {
	_u.mutation.SetActorID(v)
	return _u
}

// SetNillableActorID sets the "actor_id" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableActorID(v *string) *NotificationUpdateOne {
	if v != nil {
		_u.SetActorID(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *NotificationUpdateOne) SetType(v notification.Type) *NotificationUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableType(v *notification.Type) *NotificationUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetEntityType sets the "entity_type" field.
func (_u *NotificationUpdateOne) SetEntityType(v string) *NotificationUpdateOne {
	_u.mutation.SetEntityType(v)
	return _u
}

// SetNillableEntityType sets the "entity_type" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableEntityType(v *string) *NotificationUpdateOne {
	if v != nil {
		_u.SetEntityType(*v)
	}
	return _u
}

// SetEntityID sets the "entity_id" field.
func (_u *NotificationUpdateOne) SetEntityID(v string) *NotificationUpdateOne {
	_u.mutation.SetEntityID(v)
	return _u
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableEntityID(v *string) *NotificationUpdateOne {
	if v != nil {
		_u.SetEntityID(*v)
	}
	return _u
}

// SetData sets the "data" field.
func (_u *NotificationUpdateOne) SetData(v string) *NotificationUpdateOne {
	_u.mutation.SetData(v)
	return _u
}

// SetNillableData sets the "data" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableData(v *string) *NotificationUpdateOne {
	if v != nil {
		_u.SetData(*v)
	}
	return _u
}

// ClearData clears the value of the "data" field.
func (_u *NotificationUpdateOne) ClearData() *NotificationUpdateOne {
	_u.mutation.ClearData()
	return _u
}

// SetReadAt sets the "read_at" field.
func (_u *NotificationUpdateOne) SetReadAt(v time.Time) *NotificationUpdateOne {
	_u.mutation.SetReadAt(v)
	return _u
}

// SetNillableReadAt sets the "read_at" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableReadAt(v *time.Time) *NotificationUpdateOne {
	if v != nil {
		_u.SetReadAt(*v)
	}
	return _u
}

// ClearReadAt clears the value of the "read_at" field.
func (_u *NotificationUpdateOne) ClearReadAt() *NotificationUpdateOne {
	_u.mutation.ClearReadAt()
	return _u
}

// Mutation returns the NotificationMutation object of the builder.
func (_u *NotificationUpdateOne) Mutation() *NotificationMutation {
	return _u.mutation
}

// Where appends a list predicates to the NotificationUpdate builder.
func (_u *NotificationUpdateOne) Where(ps ...predicate.Notification) *NotificationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NotificationUpdateOne) Select(field string, fields ...string) *NotificationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Notification entity.
func (_u *NotificationUpdateOne) Save(ctx context.Context) (*Notification, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotificationUpdateOne) SaveX(ctx context.Context) *Notification {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NotificationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotificationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NotificationUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := notification.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NotificationUpdateOne) check() error {
	if v, ok := _u.mutation.RecipientID(); ok {
		if err := notification.RecipientIDValidator(v); err != nil {
			return &ValidationError{Name: "recipient_id", err: fmt.Errorf(`ent: validator failed for field "Notification.recipient_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ActorID(); ok {
		if err := notification.ActorIDValidator(v); err != nil {
			return &ValidationError{Name: "actor_id", err: fmt.Errorf(`ent: validator failed for field "Notification.actor_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := notification.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Notification.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EntityType(); ok {
		if err := notification.EntityTypeValidator(v); err != nil {
			return &ValidationError{Name: "entity_type", err: fmt.Errorf(`ent: validator failed for field "Notification.entity_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EntityID(); ok {
		if err := notification.EntityIDValidator(v); err != nil {
			return &ValidationError{Name: "entity_id", err: fmt.Errorf(`ent: validator failed for field "Notification.entity_id": %w`, err)}
		}
	}
	return nil
}

func (_u *NotificationUpdateOne) sqlSave(ctx context.Context) (_node *Notification, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notification.Table, notification.Columns, sqlgraph.NewFieldSpec(notification.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Notification.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, notification.FieldID)
		for _, f := range fields {
			if !notification.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != notification.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(notification.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(notification.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RecipientID(); ok {
		_spec.SetField(notification.FieldRecipientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActorID(); ok {
		_spec.SetField(notification.FieldActorID, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(notification.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.EntityType(); ok {
		_spec.SetField(notification.FieldEntityType, field.TypeString, value)
	}
	if value, ok := _u.mutation.EntityID(); ok {
		_spec.SetField(notification.FieldEntityID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Data(); ok {
		_spec.SetField(notification.FieldData, field.TypeString, value)
	}
	if _u.mutation.DataCleared() {
		_spec.ClearField(notification.FieldData, field.TypeString)
	}
	if value, ok := _u.mutation.ReadAt(); ok {
		_spec.SetField(notification.FieldReadAt, field.TypeTime, value)
	}
	if _u.mutation.ReadAtCleared() {
		_spec.ClearField(notification.FieldReadAt, field.TypeTime)
	}
	_node = &Notification{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
