// Code generated by ent, DO NOT EDIT.

package ent

import (
	"ArifulProtik/TownHall/ent/follow"
	"ArifulProtik/TownHall/ent/refreshtoken"
	"ArifulProtik/TownHall/ent/schema"
	"ArifulProtik/TownHall/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	followMixin := schema.Follow{}.Mixin()
	followMixinFields0 := followMixin[0].Fields()
	_ = followMixinFields0
	followFields := schema.Follow{}.Fields()
	_ = followFields
	// followDescCreatedAt is the schema descriptor for created_at field.
	followDescCreatedAt := followMixinFields0[1].Descriptor()
	// follow.DefaultCreatedAt holds the default value on creation for the created_at field.
	follow.DefaultCreatedAt = followDescCreatedAt.Default.(func() time.Time)
	// followDescUpdatedAt is the schema descriptor for updated_at field.
	followDescUpdatedAt := followMixinFields0[2].Descriptor()
	// follow.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	follow.DefaultUpdatedAt = followDescUpdatedAt.Default.(func() time.Time)
	// follow.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	follow.UpdateDefaultUpdatedAt = followDescUpdatedAt.UpdateDefault.(func() time.Time)
	// followDescFollowerID is the schema descriptor for follower_id field.
	followDescFollowerID := followFields[0].Descriptor()
	// follow.FollowerIDValidator is a validator for the "follower_id" field. It is called by the builders before save.
	follow.FollowerIDValidator = followDescFollowerID.Validators[0].(func(string) error)
	// followDescFollowingID is the schema descriptor for following_id field.
	followDescFollowingID := followFields[1].Descriptor()
	// follow.FollowingIDValidator is a validator for the "following_id" field. It is called by the builders before save.
	follow.FollowingIDValidator = followDescFollowingID.Validators[0].(func(string) error)
	// followDescID is the schema descriptor for id field.
	followDescID := followMixinFields0[0].Descriptor()
	// follow.DefaultID holds the default value on creation for the id field.
	follow.DefaultID = followDescID.Default.(func() string)
	// follow.IDValidator is a validator for the "id" field. It is called by the builders before save.
	follow.IDValidator = followDescID.Validators[0].(func(string) error)
	refreshtokenMixin := schema.RefreshToken{}.Mixin()
	refreshtokenMixinFields0 := refreshtokenMixin[0].Fields()
	_ = refreshtokenMixinFields0
	refreshtokenFields := schema.RefreshToken{}.Fields()
	_ = refreshtokenFields
	// refreshtokenDescCreatedAt is the schema descriptor for created_at field.
	refreshtokenDescCreatedAt := refreshtokenMixinFields0[1].Descriptor()
	// refreshtoken.DefaultCreatedAt holds the default value on creation for the created_at field.
	refreshtoken.DefaultCreatedAt = refreshtokenDescCreatedAt.Default.(func() time.Time)
	// refreshtokenDescUpdatedAt is the schema descriptor for updated_at field.
	refreshtokenDescUpdatedAt := refreshtokenMixinFields0[2].Descriptor()
	// refreshtoken.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	refreshtoken.DefaultUpdatedAt = refreshtokenDescUpdatedAt.Default.(func() time.Time)
	// refreshtoken.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	refreshtoken.UpdateDefaultUpdatedAt = refreshtokenDescUpdatedAt.UpdateDefault.(func() time.Time)
	// refreshtokenDescTokenHash is the schema descriptor for token_hash field.
	refreshtokenDescTokenHash := refreshtokenFields[0].Descriptor()
	// refreshtoken.TokenHashValidator is a validator for the "token_hash" field. It is called by the builders before save.
	refreshtoken.TokenHashValidator = refreshtokenDescTokenHash.Validators[0].(func(string) error)
	// refreshtokenDescID is the schema descriptor for id field.
	refreshtokenDescID := refreshtokenMixinFields0[0].Descriptor()
	// refreshtoken.DefaultID holds the default value on creation for the id field.
	refreshtoken.DefaultID = refreshtokenDescID.Default.(func() string)
	// refreshtoken.IDValidator is a validator for the "id" field. It is called by the builders before save.
	refreshtoken.IDValidator = refreshtokenDescID.Validators[0].(func(string) error)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields0[1].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields0[2].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[0].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[2].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
	// userDescEmailVerified is the schema descriptor for email_verified field.
	userDescEmailVerified := userFields[5].Descriptor()
	// user.DefaultEmailVerified holds the default value on creation for the email_verified field.
	user.DefaultEmailVerified = userDescEmailVerified.Default.(bool)
	// userDescBio is the schema descriptor for bio field.
	userDescBio := userFields[6].Descriptor()
	// user.BioValidator is a validator for the "bio" field. It is called by the builders before save.
	user.BioValidator = userDescBio.Validators[0].(func(string) error)
	// userDescAvatarURL is the schema descriptor for avatar_url field.
	userDescAvatarURL := userFields[7].Descriptor()
	// user.AvatarURLValidator is a validator for the "avatar_url" field. It is called by the builders before save.
	user.AvatarURLValidator = userDescAvatarURL.Validators[0].(func(string) error)
	// userDescBannerURL is the schema descriptor for banner_url field.
	userDescBannerURL := userFields[8].Descriptor()
	// user.BannerURLValidator is a validator for the "banner_url" field. It is called by the builders before save.
	user.BannerURLValidator = userDescBannerURL.Validators[0].(func(string) error)
	// userDescLocation is the schema descriptor for location field.
	userDescLocation := userFields[9].Descriptor()
	// user.LocationValidator is a validator for the "location" field. It is called by the builders before save.
	user.LocationValidator = userDescLocation.Validators[0].(func(string) error)
	// userDescWebsite is the schema descriptor for website field.
	userDescWebsite := userFields[10].Descriptor()
	// user.WebsiteValidator is a validator for the "website" field. It is called by the builders before save.
	user.WebsiteValidator = userDescWebsite.Validators[0].(func(string) error)
	// userDescID is the schema descriptor for id field.
	userDescID := userMixinFields0[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() string)
	// user.IDValidator is a validator for the "id" field. It is called by the builders before save.
	user.IDValidator = userDescID.Validators[0].(func(string) error)
}
