// Code generated by ent, DO NOT EDIT.

package follow

import (
	"ArifulProtik/TownHall/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Follow {
	return predicate.Follow(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Follow {
	return predicate.Follow(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Follow {
	return predicate.Follow(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Follow {
	return predicate.Follow(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Follow {
	return predicate.Follow(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Follow {
	return predicate.Follow(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Follow {
	return predicate.Follow(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Follow {
	return predicate.Follow(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Follow {
	return predicate.Follow(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Follow {
	return predicate.Follow(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Follow {
	return predicate.Follow(sql.FieldContainsFold(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Follow {
	return predicate.Follow(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Follow {
	return predicate.Follow(sql.FieldEQ(FieldUpdatedAt, v))
}

// FollowerID applies equality check predicate on the "follower_id" field. It's identical to FollowerIDEQ.
func FollowerID(v string) predicate.Follow {
	return predicate.Follow(sql.FieldEQ(FieldFollowerID, v))
}

// FollowingID applies equality check predicate on the "following_id" field. It's identical to FollowingIDEQ.
func FollowingID(v string) predicate.Follow {
	return predicate.Follow(sql.FieldEQ(FieldFollowingID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Follow {
	return predicate.Follow(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Follow {
	return predicate.Follow(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Follow {
	return predicate.Follow(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Follow {
	return predicate.Follow(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Follow {
	return predicate.Follow(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Follow {
	return predicate.Follow(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Follow {
	return predicate.Follow(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Follow {
	return predicate.Follow(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Follow {
	return predicate.Follow(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Follow {
	return predicate.Follow(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Follow {
	return predicate.Follow(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Follow {
	return predicate.Follow(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Follow {
	return predicate.Follow(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Follow {
	return predicate.Follow(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Follow {
	return predicate.Follow(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Follow {
	return predicate.Follow(sql.FieldLTE(FieldUpdatedAt, v))
}

// FollowerIDEQ applies the EQ predicate on the "follower_id" field.
func FollowerIDEQ(v string) predicate.Follow {
	return predicate.Follow(sql.FieldEQ(FieldFollowerID, v))
}

// FollowerIDNEQ applies the NEQ predicate on the "follower_id" field.
func FollowerIDNEQ(v string) predicate.Follow {
	return predicate.Follow(sql.FieldNEQ(FieldFollowerID, v))
}

// FollowerIDIn applies the In predicate on the "follower_id" field.
func FollowerIDIn(vs ...string) predicate.Follow {
	return predicate.Follow(sql.FieldIn(FieldFollowerID, vs...))
}

// FollowerIDNotIn applies the NotIn predicate on the "follower_id" field.
func FollowerIDNotIn(vs ...string) predicate.Follow {
	return predicate.Follow(sql.FieldNotIn(FieldFollowerID, vs...))
}

// FollowerIDGT applies the GT predicate on the "follower_id" field.
func FollowerIDGT(v string) predicate.Follow {
	return predicate.Follow(sql.FieldGT(FieldFollowerID, v))
}

// FollowerIDGTE applies the GTE predicate on the "follower_id" field.
func FollowerIDGTE(v string) predicate.Follow {
	return predicate.Follow(sql.FieldGTE(FieldFollowerID, v))
}

// FollowerIDLT applies the LT predicate on the "follower_id" field.
func FollowerIDLT(v string) predicate.Follow {
	return predicate.Follow(sql.FieldLT(FieldFollowerID, v))
}

// FollowerIDLTE applies the LTE predicate on the "follower_id" field.
func FollowerIDLTE(v string) predicate.Follow {
	return predicate.Follow(sql.FieldLTE(FieldFollowerID, v))
}

// FollowerIDContains applies the Contains predicate on the "follower_id" field.
func FollowerIDContains(v string) predicate.Follow {
	return predicate.Follow(sql.FieldContains(FieldFollowerID, v))
}

// FollowerIDHasPrefix applies the HasPrefix predicate on the "follower_id" field.
func FollowerIDHasPrefix(v string) predicate.Follow {
	return predicate.Follow(sql.FieldHasPrefix(FieldFollowerID, v))
}

// FollowerIDHasSuffix applies the HasSuffix predicate on the "follower_id" field.
func FollowerIDHasSuffix(v string) predicate.Follow {
	return predicate.Follow(sql.FieldHasSuffix(FieldFollowerID, v))
}

// FollowerIDEqualFold applies the EqualFold predicate on the "follower_id" field.
func FollowerIDEqualFold(v string) predicate.Follow {
	return predicate.Follow(sql.FieldEqualFold(FieldFollowerID, v))
}

// FollowerIDContainsFold applies the ContainsFold predicate on the "follower_id" field.
func FollowerIDContainsFold(v string) predicate.Follow {
	return predicate.Follow(sql.FieldContainsFold(FieldFollowerID, v))
}

// FollowingIDEQ applies the EQ predicate on the "following_id" field.
func FollowingIDEQ(v string) predicate.Follow {
	return predicate.Follow(sql.FieldEQ(FieldFollowingID, v))
}

// FollowingIDNEQ applies the NEQ predicate on the "following_id" field.
func FollowingIDNEQ(v string) predicate.Follow {
	return predicate.Follow(sql.FieldNEQ(FieldFollowingID, v))
}

// FollowingIDIn applies the In predicate on the "following_id" field.
func FollowingIDIn(vs ...string) predicate.Follow {
	return predicate.Follow(sql.FieldIn(FieldFollowingID, vs...))
}

// FollowingIDNotIn applies the NotIn predicate on the "following_id" field.
func FollowingIDNotIn(vs ...string) predicate.Follow {
	return predicate.Follow(sql.FieldNotIn(FieldFollowingID, vs...))
}

// FollowingIDGT applies the GT predicate on the "following_id" field.
func FollowingIDGT(v string) predicate.Follow {
	return predicate.Follow(sql.FieldGT(FieldFollowingID, v))
}

// FollowingIDGTE applies the GTE predicate on the "following_id" field.
func FollowingIDGTE(v string) predicate.Follow {
	return predicate.Follow(sql.FieldGTE(FieldFollowingID, v))
}

// FollowingIDLT applies the LT predicate on the "following_id" field.
func FollowingIDLT(v string) predicate.Follow {
	return predicate.Follow(sql.FieldLT(FieldFollowingID, v))
}

// FollowingIDLTE applies the LTE predicate on the "following_id" field.
func FollowingIDLTE(v string) predicate.Follow {
	return predicate.Follow(sql.FieldLTE(FieldFollowingID, v))
}

// FollowingIDContains applies the Contains predicate on the "following_id" field.
func FollowingIDContains(v string) predicate.Follow {
	return predicate.Follow(sql.FieldContains(FieldFollowingID, v))
}

// FollowingIDHasPrefix applies the HasPrefix predicate on the "following_id" field.
func FollowingIDHasPrefix(v string) predicate.Follow {
	return predicate.Follow(sql.FieldHasPrefix(FieldFollowingID, v))
}

// FollowingIDHasSuffix applies the HasSuffix predicate on the "following_id" field.
func FollowingIDHasSuffix(v string) predicate.Follow {
	return predicate.Follow(sql.FieldHasSuffix(FieldFollowingID, v))
}

// FollowingIDEqualFold applies the EqualFold predicate on the "following_id" field.
func FollowingIDEqualFold(v string) predicate.Follow {
	return predicate.Follow(sql.FieldEqualFold(FieldFollowingID, v))
}

// FollowingIDContainsFold applies the ContainsFold predicate on the "following_id" field.
func FollowingIDContainsFold(v string) predicate.Follow {
	return predicate.Follow(sql.FieldContainsFold(FieldFollowingID, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Follow) predicate.Follow {
	return predicate.Follow(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Follow) predicate.Follow {
	return predicate.Follow(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Follow) predicate.Follow {
	return predicate.Follow(sql.NotPredicates(p))
}
